<?xml version="1.0"?>
<package format="3">
  <name>xgo_voice_doubao</name>
  <version>0.0.1</version>
  <description>Subscribe to doubao_asr text and control XGO via xgolib</description>
  <maintainer email="noreply@example.com">xgo</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>std_msgs</depend>
  <depend>xgolib</depend>

  <export></export>
</package>